name: media_kit
description: A cross-platform video player & audio player for Flutter & Dart. Performant, stable, feature-proof & modular.
homepage: https://github.com/media-kit/media-kit
repository: https://github.com/media-kit/media-kit
version: 1.1.11

screenshots:
  - description: "package:media_kit running on Android (visible controls)"
    path: screenshots/android_0.jpg
  - description: "package:media_kit running on Android"
    path: screenshots/android_1.jpg
  - description: "package:media_kit running on iOS (visible controls)"
    path: screenshots/ios_0.jpg
  - description: "package:media_kit running on iOS"
    path: screenshots/ios_1.jpg
  - description: "package:media_kit running on macOS"
    path: screenshots/macos.jpg
  - description: "package:media_kit running on Microsoft Windows"
    path: screenshots/windows.jpg
  - description: "package:media_kit running on GNU/Linux"
    path: screenshots/linux.jpg
  - description: "package:media_kit running on web"
    path: screenshots/web.jpg
topics:
  - video
  - video-player
  - audio
  - audio-player
  - cross-platform

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  meta: ^1.16.0
  path: ^1.9.1
  image: ^4.5.4
  uri_parser: ^3.0.0
  collection: ^1.19.1
  synchronized: ^3.3.1
  uuid: ">=4.5.1 <5.0.0"
  http: ">=1.4.0 <2.0.0"
  safe_local_storage: ^2.0.1
  universal_platform: ^1.0.0+1
  web: ^1.1.1
dev_dependencies:
  test: ^1.26.0
  lints: ^5.0.0

ffigen:
  name: MPV
  output: bin/generated/libmpv/bindings.dart
  headers:
    entry-points:
      - headers/client.h
  dart-bool: true

flutter:
  assets:
    - assets/web/
